config/routes.rb
Rails.application.routes.draw do
  
  root to: 'toppages#index'
  get 'toppage', to: 'toppages#index'
  get 'everyones/:id', to: 'toppages#show'
  get 'help', to: 'toppages#help'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :create]
  
  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#destroy'
  
  get 'points/new/:collection', to: 'points#new'
  post 'points/:collection', to: 'points#create'
  get 'points/show/:collection/:id', to: 'points#show'
  get 'points/:collection/:id/edit', to: 'points#edit'
  patch 'points/:collection/:id', to: 'points#update'
  delete 'points/:collection/:id/', to: 'points#destroy'
  
  resources :collections
  get 'collection_info/:id', to: 'collections#info'
  get 'show_public', to: 'collections#show_public'
  
  resources :collection_relationships, only: [:create, :destroy]
  
  resources :comments, only: [:create, :destroy]
  
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  
  validates :name, length: {maximum: 50}
  validates :collection_type, numericality: {
            only_integer: true, 
            greater_than_or_equal_to: 0,
            less_than_or_equal_to: 1
          }
  
  has_many :points, dependent: :destroy
  has_many :collection_relationships, dependent: :destroy
  has_many :followers, through: :collection_relationships, source: :user
  
  mount_uploader :image, ImageUploader
  
  def is_private?
    self.collection_type == 1
  end
  
  def is_public?
    self.collection_type == 0
  end
  
  def creator
    User.find_by(id: self.created_by)
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :require_user_logged_in
  before_action :set_collection, only: [:show, :edit, :update, :destroy, :info]
  before_action :set_edit_control, only: [:info, :edit, :update, :destroy]
    
  def new
    @collection = Collection.new
  end

  def create
    prms = collection_params
    
    if prms[:collection_type] == 0                      # Public Collection
      @collection = public_user.collections.build(prms)
    else                                                # Private Collection
      @collection = current_user.collections.build(prms)
    end
    
    if prms[:name] == nil || prms[:name] == ''
      flash.now[:danger] = 'コレクション名は必須です。'
      render :new
    elsif prms[:name].size > 40
      flash.now[:danger] = 'コレクション名は40文字までです。'
      render :new
    elsif prms[:collection_type] < 0 || prms[:collection_type] > 1
      flash.now[:danger] = '正しくないデータが入力されました。'
      render :new
    else
      if @collection.save
        
        if @collection.collection_type == 0
          current_user.follow(@collection)
        end
        
        flash[:success] = 'コレクションを作成しました!'
        redirect_to controller: 'collections', action: 'show', id: @collection
      else
        flash.now[:danger] = 'コレクションの作成に失敗しました。'
        render :new
      end
    end
  end
  
  def edit
    redirect_to root_url if !@edit_control
  end

  def update
    redirect_to root_url if !@edit_control
    
    prms = collection_params
    
    if prms[:name] == ''
      flash.now[:danger] = 'コレクション名は必須です。'
      render :edit
    elsif prms[:collection_type] < 0 || prms[:collection_type] > 1
      flash.now[:danger] = '正しくないデータが入力されました。'
      render :edit
    elsif @collection.followers.size >=2 && prms[:collection_type] != @collection.collection_type
      flash.now[:danger] = "#{current_user.name}さん以外にフォロワーが存在するためコレクションのタイプを変更できません。"
      render :edit
    else # パラメータにエラーが無いとき
      if prms[:collection_type] == 0 && @collection.collection_type == 1 # privateからpublicに変更するとき
        prms[:user_id] = 1
        current_user.follow(@collection)
      end
      
      prms[:image] ||= @collection.image
      
      if @collection.update(prms)
        flash[:success] = 'コレクション情報を更新しました!'
        redirect_to controller: 'collections', action: 'info', id: @collection
      else
        flash.now[:danger] = 'コレクション情報の更新に失敗しました。'
        render :edit
      end
    end
  end
  
  def info
   
  end
  
  def index
    @collections = current_user.collections
    @follow_collections = current_user.follow_collections
    
    if @collections.size != 0
      @collection = @collections.order(:updated_at).last
      @points = @collection.points.all
      @no_collection = false
    else
      @no_collection = true
      @collection = Collection.new(name: "←メニューを開いてコレクションを作成しましょう! ")
    end
  end

  def show
    @points = @collection.points.all
  end
  
  def show_public
    @public_collections = public_user.collections
  end
  
   def destroy
    redirect_to root_url if !@edit_control
    
    if @collection.followers.size < 2
      @collection.destroy
    
      flash[:success] = 'コレクションを削除しました。'
      redirect_to root_url
    else
      flash.now[:danger]  = "#{current_user.name}さん以外にフォロワーが存在するためコレクションを削除できません。"
      render :edit
    end
  end
  
  private
  
  def collection_params
    prms = params.require(:collection).permit(:name, :description, :collection_type, :image)
    
    prms[:collection_type] = prms[:collection_type].to_i
    
    prms[:created_by] = current_user.id
    
    prms
  end
  
  def set_collection()
    @collections = current_user.collections
    @follow_collections = current_user.follow_collections
    
    @collection = @collections.find_by(id: params[:id]) 
    @collection ||= find_from_public_collection(params[:id])
    
    redirect_to root_url if @collection == nil
  end
  
  def set_edit_control
    @edit_control = @collection.user.id == current_user.id || @collection.created_by == current_user.id
  end
  
end

app/views/collections/_delete_msg.html.erb
<!-- Delete Point Dialog -->
<div class="modal fade" id="delete_dialog" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      
      <!-- Header -->
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
        </button>
          <h4 class="modal-title" id="modal-label">確認!</h4>
      </div>
      
      <!-- Body -->
      <div class="modal-body">
        <p>このコレクションをを削除してもよろしいですか？</p>
        <p>(注意：コレクションに登録されているポイントも削除されます。)</p>
      </div>
      
      <!-- Footer-->
      <div class="modal-footer">
        <%= link_to 'Yes', @collection, method: :delete, class: 'btn btn-danger' %>
        <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
      </div>
    </div>
  </div>
</div>

app/views/collections/_edit_form.html.erb
<div class="formcontainer">
  <div class="container">
    <%= form_for(@collection) do |f| %>
      <div class="row">
        <!-- Description Box -->
        <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-0">
          <div class="form-group">
            <%= f.label :name, 'コレクション名' %>
            <%= f.text_field :name, class: 'form-control', placeholder: 'コレクションの名前' %>
          </div>
          <div class="form-group">
            <%= f.label :description, '説明' %>
            <%= f.text_area :description, class: 'form-control', rows:8, placeholder: '場所の詳しい説明やメモなど' %>
          </div>
          <% if @collection.followers.size >= 2 %>
             <div class="form-group">
              <%= f.label :collection_type, 'コレクションのタイプ' %>
              <%= f.select :collection_type, {Private: 1, Public: 0}, {}, { :disabled => "disabled" }%>
              <p>(※)コレクションのフォロワー数が2以上なのでタイプを変更できません。</p>
            </div>
          <% else %>
            <div class="form-group">
              <%= f.label :collection_type, 'コレクションのタイプ' %>
              <%= f.select :collection_type, {Private: 1, Public: 0} %>
            </div>
          <% end %>
        </div>
        
        <!-- Photo Box -->
        <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-0">
          <div class="form-group">
            <%= f.label :image, 'コレクションのイメージ' %>
            <div class="photo-form-box">
              <% if @collection.image? %>
              <%= image_tag @collection.image.thumb.url %>
            <% else %>
              <div class="noimage"><span class="glyphicon glyphicon-picture"></span></div>
            <% end %>
            </div>
          </div>
          
          <div class="form-group">
            <%= f.file_field :image %>
            <%= f.hidden_field :image_cache %>
          </div>
          
        </div>
      </div>
      
      <div class="point_btns_container">
        <div class="row">
          <% if type == :new %>
            <%= render 'collections/save_msg', f: f %>
            <div class="col-xs-4 col-xs-offset-4">
              <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#save_dialog">保存</button>
            </div>
            <div class="col-xs-2">
              <%= link_to '戻る', root_url, class: 'btn btn-default btn-block'%>
            </div>
          <% elsif type == :edit %>
            <%= render 'collections/update_msg', f: f %>
            <%= render 'collections/delete_msg' %>
            
            <div class="col-xs-4 col-sm-2 col-sm-offset-6">
              <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#update_dialog">保存</button>
            </div>
            <div class="col-xs-4 col-sm-2">
              <button type="button" class="btn btn-danger btn-block" data-toggle="modal" data-target="#delete_dialog">削除</button>
            </div>
            <div class="col-xs-4 col-sm-2">
              <%= link_to '戻る', "/collection_info/#{@collection.id}", class: 'btn btn-default btn-block'%>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/collections/_save_msg.html.erb
<!-- Update Point Dialog -->
<div class="modal fade" id="save_dialog" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      
      <!-- Header -->
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
        </button>
          <h4 class="modal-title" id="modal-label">確認!</h4>
      </div>
      
      <!-- Body -->
      <div class="modal-body">
        コレクション情報を保存してもよろしいですか？
      </div>
      
      <!-- Footer-->
      <div class="modal-footer">
        <%= f.submit 'Yes', class: 'btn btn-primary' %>
        <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
      </div>
    </div>
  </div>
</div>

app/views/collections/_show_collection.html.erb
<div id="st-container" class="st-container">
	
	<nav class="st-menu st-effect-2" id="menu-2">
	  <div class="clearfix">
		  <h2>Myコレクション</h2>
		  <%= link_to new_collection_path do %>
		  	<span class="glyphicon glyphicon-plus-sign plus-icon" title="コレクションを作成しましょう！"></span>
		  <% end %>
		</div>
		
		<ul>
			<% if @collections.size == 0 %>
				<li><%= link_to 'コレクションを作ろう!', new_collection_path %></li>
			<% else %>
					<% @collections.each do |c| %>
					<li>
						<%= link_to c.name, c %>
					</li>
				<% end %>
			<% end %>
		</ul>
		
		<div class="clearfix">
		  <h2>フォロー</h2>
		  <%= link_to '/show_public' do %>
		  	<span class="glyphicon glyphicon-search plus-icon" title="お気に入りのパブリックコレクションを見つけてフォローしよう！"></span>
		  <% end %>
		</div>
		<ul>
			<% @follow_collections.each do |item| %>
				<li><%= link_to item.name, item %></li>
			<% end %>
		</ul>
	</nav>
	
	<div class="st-pusher">
		
		<div class="st-content">
			
			<div class="st-content-inner">
				<!-- Top Navigation -->
        			
				<div class="main">
	        <div id="st-trigger-effects"><button data-effect="st-effect-2" class="open-menu glyphicon glyphicon-option-vertical"></button></div>	
					<%= render 'layouts/flash_messages' %>
          
					<%= render 'layouts/gmap' %>
					
					<%= render 'toppages/point_list' %>
						
				</div><!-- /main -->
				
				<%= render 'layouts/footer' %>
				
			</div><!-- /st-content-inner -->
		</div><!-- /st-content -->
    
	</div><!-- /st-pusher -->

</div><!-- /st-container -->

app/views/collections/_update_msg.html.erb
<!-- Update Point Dialog -->
<div class="modal fade" id="update_dialog" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      
      <!-- Header -->
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
        </button>
          <h4 class="modal-title" id="modal-label">確認!</h4>
      </div>
      
      <!-- Body -->
      <div class="modal-body">
         コレクション情報を更新してもよろしいですか？
      </div>
      
      <!-- Footer-->
      <div class="modal-footer">
        <%= f.submit 'Yes', class: 'btn btn-primary' %>
        <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
      </div>
    </div>
  </div>
</div>

app/views/collections/edit.html.erb
<h1 class="collection_name">コレクションの編集</h1>

<%= render 'collections/edit_form', type: :edit %>

app/views/collections/index.html.erb
<%= render 'collections/show_collection' %>

app/views/collections/info.html.erb
<h1 class="collection_name"><%= @collection.name %></h1>

<div class="formcontainer">
  <div class="container">
    <div class="row">
      <!-- Description Box -->
      <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-0">
        <div class="point_infomation">
          <table class="table">
            <tr>
              <td class="point_tbllabel">コレクション名</td>
              <td class="text-left"><%= @collection.name %></td>
            </tr>
            <tr>
              <td class="point_tbllabel">タイプ</td>
              <% if @collection.is_public? %>
                <td class="text-left">Public</td>
              <% else %>
                <td class="text-left">Private</td>
              <% end %>
            </tr>
            <tr>
              <td class="point_tbllabel">作成日</td>
              <td class="text-left"><%= @collection.created_at.strftime("%Y-%m-%d") %></td>
            </tr>
            <% if @collection.is_public? %>
              <tr>
                <td class="point_tbllabel">作成者</td>
                <td class="text-left">
                  <img class="media-object img-rounded img-responsive" src="
                  <%= gravatar_url(User.find(@collection.creator.id), { size: 50 }) %>
                  " alt="">
                  <%= @collection.creator.name %>
                </td>
              </tr>
            <% end %>
            <tr>
              <td class="point_tbllabel">登録ポイント数</td>
              <td class="text-left"><%= @collection.points.size %></td>
            </tr>
            <% if @collection.is_public? %>
              <tr>
                <td class="point_tbllabel">フォロワー数</td>
                <td class="text-left"><%= @collection.followers.size %></td>
              </tr>
            <% end %>
            <tr>
              
            </tr>
          </table>
          <div class="point_container">
            <span class="pointlabel">説明</span>
            <pre class="pointdescription"><%= @collection.description %></pre>
          </div>
        </div>
      </div>  
      
      <!-- Photo Box -->
      <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-0">
        <div class="pointlabel">コレクションイメージ</div>
        <div class="photo-form-box">
          <% if @collection.image? %>
            <%= image_tag @collection.image.thumb.url %>
          <% else %>
            <div class="noimage"><span class="glyphicon glyphicon-picture"></span></div>
        　<% end %>
        </div>
        </div>
      </div>
    </div>
    
    <div class="point_btns_container">
      <div class="row">
   
        <% if current_user.is_creator?(@collection) %>
          <div class="col-xs-3 col-xs-offset-5 col-md-2 col-md-offset-7">
            <%= link_to '編集', edit_collection_path(@collection), class: 'btn btn-primary btn-block'%>
          </div>
          <div class="col-xs-3  col-md-2">
            <%= link_to '戻る', root_url, class: 'btn btn-default btn-block'%>
          </div>
        <% else %>
        
          <% if current_user.following?(@collection) %>
          
            <%= form_for(current_user.collection_relationships.find_by(collection_id: @collection.id), html: { method: :delete }) do |f| %>
              <%= hidden_field_tag :collection_id, @collection.id %>
              <%= f.submit 'アンフォロー', class: 'col-xs-4 col-xs-offset-3 col-md-2 col-md-offset-7 btn btn-warning'%>
            <% end %>
            
          <% else %>
            
            <%= form_for(current_user.collection_relationships.build) do |f| %>
              <%= hidden_field_tag :collection_id, @collection.id %>
              
              <%= f.submit 'フォロー', class: 'col-xs-4 col-xs-offset-3 col-md-2  col-md-offset-7 btn btn-success'%>
            
            <% end %>
        
          <% end %>
            
          <div class="col-xs-3 col-md-2">
            <%= link_to '戻る', root_url, class: 'btn btn-default btn-block'%>
          </div>
          
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/collections/new.html.erb
<h1 class="collection_name">コレクションを作ろう！</h1>

<%= render 'collections/edit_form', type: :new %>

app/views/collections/show.html.erb
<%= render 'collections/show_collection' %>

app/views/collections/show_public.html.erb
<h1 class="collection_name">みんなのコレクション</h1>

<% if @public_collections %>
  <div class="container">
    <div class="row">
      
      <div class="tablecontainer">
        <table class="table table-striped collections_table">
          <tr>
            <th class="col-xs-2 col-md-1"></th>
            <th class="col-xs-2 col-md-1">名前</th>
            <th class="col-xs-4 col-md-5">説明</th>
            <th class="col-xs-2 col-md-1"></th>
            <th class="col-xs-2 col-md-1"></th>
          </tr>
          
          <% @public_collections.each do |item| %>
          <tr>
            <td>
              <div class="icon">
               <% if item.image? %>
                  <%= image_tag item.image.thumb.url %>
                <% else %>
                  <div class="noimage"><span class="glyphicon glyphicon-picture"></span></div>
              　<% end %>
              </div>
            </td>
            <td><span><%= link_to item.name, :controller => 'collections', :action => 'info', :id => item.id %> </div></td>
            <td><span class="textoverflow"><%= item.description %></span></td>
            <td><span  class="badge"><%= item.points.size %> Points</span></td>
            <td><span  class="badge"><%= item.followers.size %> Users</span></td>
          </tr>
          <% end %>
        </table>
  
      </div>
    </div>
  </div>
<% end %>